### ISSUE TITLE
Resolve console errors in example pages

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-ui.com#34]
# Issue Description
Some of the examples are throwing console errors when viewing them.

The following pages are throwing errors:

- [x] Datepicker
- [x] Forms
- [x] Time Input
- [ ] Status - only throws error when served over https. Issue with img resource coming from http url.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Example pages don't throw console errors.

## Current Behavior
Some of the example pages throw console errors.

## Steps to Reproduce
1. Navigate to the documentation pages for the components above
2. Open the developer console

**Comment by Matt-Butler** [comment]
Datepicker, forms, and time input was resolved here:
https://github.com/cerner/terra-ui.com/pull/33

The image for status needs to be updated in terra-core. I logged an issue for that in the terra-core repo:
https://github.com/cerner/terra-core/issues/526
