### ISSUE TITLE
Switch from webpacker_lite to webpacker.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-ui.com#55]
# Issue Description
Webpacker is available for our applications to use. To get this app as a good example app for our teams, we need to switch over to using webpacker.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

**Comment by mjhenkes** [comment]
This site will switch to being a static site hosted on gh-pages. Webpacker will no longer be needed.
