### ISSUE TITLE
terra-ui.com not accessable (or expired)

### ISSUE THREAD

**Issue by ericterpstra** [cerner/terra-ui.com#9]
I was hoping to check out the component lib after reading your [blog post](http://engineering.cerner.com/blog/building-a-unified-ui-component-library/). The site does not seem to exist any longer :/ 

### Description of Issue
Navigating to http://terra-ui.com goes to a GoDaddy placeholder page.  https://www.terra-ui.com is unaccessable.

#### Browser and Version
Chrome (latest)

**Comment by Matt-Butler** [comment]
Hey @ericterpstra 
, thanks for reaching out to us. 

The Terra documentation site is in an early stage of development.  We are working on getting a design for the site and adding more components. Once that work as been completed, it will be accessible at terra-ui.com 

If you are curious about the components we have so far, we have a prototype site deployed at https://terra-ui-staging.herokuapp.com/.  At this point, it is mostly used for testing.

Hope this helps!

**Comment by Matt-Butler** [comment]
We are now using the domain name terra-ui.com
